"""AWS Bedrock LLM integration."""

import json
import boto3
from typing import Optional, List, Any, Iterator
from langchain_core.language_models import BaseLLM
from langchain_core.outputs import Generation, LLMResult
from langchain_core.callbacks import CallbackManagerForLLMRun
from pydantic import Field
from rag_ecosystem.utils.logger import setup_logger

logger = setup_logger("bedrock_llm")


class BedrockLLM(BaseLLM):
    """AWS Bedrock LLM wrapper for LangChain."""

    model_id: str = Field(default="anthropic.claude-3-sonnet-20240229-v1:0")
    region_name: str = Field(default="us-east-1")
    temperature: float = Field(default=0.0)
    max_tokens: int = Field(default=2048)
    top_p: float = Field(default=0.9)

    bedrock_client: Any = Field(default=None, exclude=True)

    class Config:
        """Configuration for this pydantic object."""
        extra = "forbid"

    def __init__(self, **kwargs):
        """Initialize Bedrock LLM."""
        super().__init__(**kwargs)

        # Initialize Bedrock client
        if self.bedrock_client is None:
            self.bedrock_client = boto3.client(
                service_name="bedrock-runtime",
                region_name=self.region_name
            )

        logger.info(f"Initialized Bedrock LLM with model: {self.model_id}")

    @property
    def _llm_type(self) -> str:
        """Return type of LLM."""
        return "bedrock"

    def _call(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> str:
        """Call Bedrock model.

        Args:
            prompt: The prompt to pass into the model
            stop: Optional list of stop sequences
            run_manager: Callback manager

        Returns:
            The string generated by the model
        """
        # Prepare request based on model family
        if "anthropic.claude" in self.model_id:
            body = self._prepare_claude_request(prompt, stop)
        elif "amazon.titan" in self.model_id:
            body = self._prepare_titan_request(prompt, stop)
        elif "meta.llama" in self.model_id:
            body = self._prepare_llama_request(prompt, stop)
        elif "cohere" in self.model_id:
            body = self._prepare_cohere_request(prompt, stop)
        elif "ai21" in self.model_id:
            body = self._prepare_ai21_request(prompt, stop)
        else:
            raise ValueError(f"Unsupported model: {self.model_id}")

        try:
            # Invoke model
            response = self.bedrock_client.invoke_model(
                modelId=self.model_id,
                body=json.dumps(body)
            )

            # Parse response
            response_body = json.loads(response["body"].read())

            # Extract text based on model family
            if "anthropic.claude" in self.model_id:
                text = response_body.get("content", [{}])[0].get("text", "")
            elif "amazon.titan" in self.model_id:
                text = response_body.get("results", [{}])[0].get("outputText", "")
            elif "meta.llama" in self.model_id:
                text = response_body.get("generation", "")
            elif "cohere" in self.model_id:
                text = response_body.get("generations", [{}])[0].get("text", "")
            elif "ai21" in self.model_id:
                text = response_body.get("completions", [{}])[0].get("data", {}).get("text", "")
            else:
                text = str(response_body)

            return text

        except Exception as e:
            logger.error(f"Error calling Bedrock: {str(e)}")
            raise

    def _prepare_claude_request(self, prompt: str, stop: Optional[List[str]] = None) -> dict:
        """Prepare request for Claude models."""
        body = {
            "anthropic_version": "bedrock-2023-05-31",
            "max_tokens": self.max_tokens,
            "temperature": self.temperature,
            "top_p": self.top_p,
            "messages": [
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        }

        if stop:
            body["stop_sequences"] = stop

        return body

    def _prepare_titan_request(self, prompt: str, stop: Optional[List[str]] = None) -> dict:
        """Prepare request for Amazon Titan models."""
        body = {
            "inputText": prompt,
            "textGenerationConfig": {
                "maxTokenCount": self.max_tokens,
                "temperature": self.temperature,
                "topP": self.top_p,
            }
        }

        if stop:
            body["textGenerationConfig"]["stopSequences"] = stop

        return body

    def _prepare_llama_request(self, prompt: str, stop: Optional[List[str]] = None) -> dict:
        """Prepare request for Meta Llama models."""
        body = {
            "prompt": prompt,
            "max_gen_len": self.max_tokens,
            "temperature": self.temperature,
            "top_p": self.top_p,
        }

        return body

    def _prepare_cohere_request(self, prompt: str, stop: Optional[List[str]] = None) -> dict:
        """Prepare request for Cohere models."""
        body = {
            "prompt": prompt,
            "max_tokens": self.max_tokens,
            "temperature": self.temperature,
            "p": self.top_p,
        }

        if stop:
            body["stop_sequences"] = stop

        return body

    def _prepare_ai21_request(self, prompt: str, stop: Optional[List[str]] = None) -> dict:
        """Prepare request for AI21 models."""
        body = {
            "prompt": prompt,
            "maxTokens": self.max_tokens,
            "temperature": self.temperature,
            "topP": self.top_p,
        }

        if stop:
            body["stopSequences"] = stop

        return body

    def _generate(
        self,
        prompts: List[str],
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> LLMResult:
        """Generate text for multiple prompts."""
        generations = []
        for prompt in prompts:
            text = self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
            generations.append([Generation(text=text)])

        return LLMResult(generations=generations)

    def _stream(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> Iterator[str]:
        """Stream output from Bedrock (if supported)."""
        # For models that support streaming
        if "anthropic.claude" in self.model_id:
            body = self._prepare_claude_request(prompt, stop)

            try:
                response = self.bedrock_client.invoke_model_with_response_stream(
                    modelId=self.model_id,
                    body=json.dumps(body)
                )

                for event in response.get("body"):
                    chunk = json.loads(event["chunk"]["bytes"])

                    if chunk.get("type") == "content_block_delta":
                        delta = chunk.get("delta", {})
                        if delta.get("type") == "text_delta":
                            text = delta.get("text", "")
                            yield text

            except Exception as e:
                logger.error(f"Error streaming from Bedrock: {str(e)}")
                # Fallback to non-streaming
                yield self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
        else:
            # Non-streaming models
            yield self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)


def get_bedrock_llm(
    model_id: str = "anthropic.claude-3-sonnet-20240229-v1:0",
    region_name: str = "us-east-1",
    temperature: float = 0.0,
    max_tokens: int = 2048,
) -> BedrockLLM:
    """Create a Bedrock LLM instance.

    Args:
        model_id: Bedrock model ID
        region_name: AWS region
        temperature: Temperature for generation
        max_tokens: Maximum tokens to generate

    Returns:
        BedrockLLM instance
    """
    return BedrockLLM(
        model_id=model_id,
        region_name=region_name,
        temperature=temperature,
        max_tokens=max_tokens,
    )
